env:
  DOCKER_TAG: myapp
steps:
  - name: ":docker: Build"
    command: .buildkite/docker_build
    agents:
      docker: true
  - wait
  - name: ":hammer: Test"
    command: .buildkite/test
    agents:
      docker: true
